version: 2.0.{build}

branches:
  only:
    - master
  except:
    - gh-pages

skip_tags: true
skip_branch_with_pr: true

clone_folder: C:\Projects\NCredStash

shallow_clone: true

matrix:
  fast_finish: true

cache:
  - packages -> **\packages.config

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

nuget:
  disable_publish_on_pr: true

platform: Any CPU
configuration: Release

before_build:
- ps: nuget restore

build:
  publish_nuget: true
  publish_nuget_symbols: true

deploy:
- provider: GitHub
  auth_token:
    secure: HJ2BBqF1As8CM3wNl5558hAR/u5LClT+PBrHIT9G4Kvl5/vME2NAWtVLQctYjzoq
  on:
    branch: master
    appveyor_repo_tag: false
- provider: NuGet
  api_key:
    secure: V4shumgGdi9wQM6i6BpHk3JlUNrx1yFWj7ISQaBvslqcJXSpLXS/zMprWxFekixJ
  on:
    branch: master
    appveyor_repo_tag: false
