version: 3.1.{build}

branches:
  only:
    - master
  except:
    - gh-pages

skip_tags: true
skip_branch_with_pr: true
skip_commits:
  files:
    - README.md

clone_folder: C:\Projects\NCredStash

shallow_clone: true

matrix:
  fast_finish: true

cache:
  - '%USERPROFILE%\.nuget\packages'

nuget:
  disable_publish_on_pr: true

platform: Any CPU
configuration: Release

image:
- Visual Studio 2017

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

before_build:
  - dotnet restore

build:
  publish_nuget: true
  publish_nuget_symbols: true

build_script:
  - dotnet msbuild src\NCredStash /p:Configuration=%CONFIGURATION%
  - dotnet msbuild src\NCredStash.Tests /p:Configuration=%CONFIGURATION%
  
test_script:
  - dotnet test test\NCredStash.Tests -c %CONFIGURATION%
