version: 3.0.{build}

branches:
  only:
    - master
  except:
    - gh-pages

skip_tags: true
skip_branch_with_pr: true

clone_folder: C:\Projects\NCredStash

shallow_clone: true

matrix:
  fast_finish: true

cache:
  - '%USERPROFILE%\.nuget\packages'

nuget:
  disable_publish_on_pr: true

platform: Any CPU
configuration: Release

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

before_build:
  - dotnet restore
  - ps: tools\Update-Projects-Version.ps1

build:
  publish_nuget: true
  publish_nuget_symbols: true

build_script:
  - dotnet build src\NCredStash
  - dotnet build test\NCredStash.Tests
  
test_script:
  - dotnet test test\NCredStash.Tests

before_deploy:
  - dotnet pack --no-build src\NCredStash\project.json
  
deploy:
- provider: GitHub
  auth_token:
    secure: HJ2BBqF1As8CM3wNl5558hAR/u5LClT+PBrHIT9G4Kvl5/vME2NAWtVLQctYjzoq
  on:
    branch: master
    appveyor_repo_tag: false
- provider: NuGet
  api_key:
    secure: V4shumgGdi9wQM6i6BpHk3JlUNrx1yFWj7ISQaBvslqcJXSpLXS/zMprWxFekixJ
  on:
    branch: master
    appveyor_repo_tag: false
